# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.
# The lines in this template starting with the hashtag symbol are 
#   instructional comments and can be safely left in the file or 
#   ignored.
# For help completing this file, see the "AppSpec File Reference" in the  
#   "CodeDeploy User Guide" at
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
# Specify "os: linux" if this revision targets Amazon Linux, 
#   Red Hat Enterprise Linux (RHEL), or Ubuntu Server  
#   instances.
# Specify "os: windows" if this revision targets Windows Server instances.
# (You cannot specify both "os: linux" and "os: windows".)
#os: linux 
os: windows
files:
  - source: 
    destination: C:\inetpub\wwwroot\Opserver 
# If you do not want to run any commands during a particular deployment
#   lifecycle event, remove that event declaration altogether. Blank or 
#   incomplete event declarations may cause associated deployments to fail.
# During the ApplicationStop deployment lifecycle event, run the commands 
#   in the script specified in "location" starting from the root of the 
#   revision's file bundle.
#hooks:
#  AfterInstall:
#    - location: afterinstall.ps1
#      timeout: 900
#      runas:
#    - location: 
#      timeout:
#      runas:
# During the ApplicationStart deployment lifecycle event, run the commands 
#   in the script specified in "location".
# ApplicationStart:
#    - location:     
#      timeout: 
#      runas:
#    - location: 
#      timeout:
#      runas:
# During the ValidateService deployment lifecycle event, run the commands 
#   in the script specified in "location".
#  ValidateService:
#    - location:     
#      timeout: 
#      runas:
#    - location: 
#      timeout:
#      runas:
